on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to test Go fuzzing
    steps:
      - name: Hello Fuzzing
        uses: ottotech/go-fuzzing-test@v1.1
