on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to test Go fuzzing
    steps:
      - name: Hello world action step
        id: hello
        uses: actions/go-fuzzing-test@master